USE NS2_VP_Prod_Stage
GO
DROP TABLE #temp
CREATE TABLE #temp(Field nvarchar(256))
INSERT INTO #temp(Field)
EXEC Proc_NS_VP_Prod_Staging_Table_Fields @Tbl = 'customer'
SELECT
	WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ',' AS FieldNames,
	CASE
		WHEN Tc.TYPE_NAME = 'TIMESTAMP' THEN 'WFDW.dbo.fn_DateTime(' + WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ') AS ' +  WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) +','
		ELSE WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ','
	END AS ColumnText,
	'''' + WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + '''' + ',' AS ColumnSELECTText,
	WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ' ' +
	CASE
		WHEN Tc.TYPE_NAME = 'INTEGER' THEN 'INT'
		WHEN Tc.TYPE_NAME = 'NUMBER' AND Tc.OA_SCALE <> 0 THEN 'FLOAT'
		WHEN Tc.TYPE_NAME = 'SMALLINT' THEN 'SMALLINT'
		WHEN Tc.TYPE_NAME = 'BIGINT' THEN 'BIGINT'
		WHEN Tc.TYPE_NAME = 'DOUBLE' THEN 'BIGINT'
		WHEN Tc.TYPE_NAME = 'CLOB' THEN 'CLOB'
		WHEN Tc.TYPE_NAME = 'TIMESTAMP' THEN 'DATETIME2'
		WHEN Tc.TYPE_NAME = 'CHAR' THEN 'CHAR(' + CAST(Tc.OA_PRECISION AS nvarchar) + ')'
		WHEN Tc.TYPE_NAME = 'VARCHAR2' THEN 'NVARCHAR(' + CAST(Tc.OA_PRECISION AS nvarchar) + ')'
		ELSE 'Unknown'
	END + ',' AS TableText,
	'TARGET.' + WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ' = ' +'SOURCE.' + WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ',' AS [UpdateText],
	'SOURCE.' + WFDW.dbo.fn_ReservedNames(Tc.COLUMN_NAME) + ',' AS [InsertText]

FROM
	NS2_VP_Prod_Stage.dbo._NetSuite_TableColumns Tc
WHERE
	TABLE_NAME = 'customer'
	AND Tc.TYPE_NAME <> 'CLOB'
	--AND OA_PRECISION >= 4000
	AND COLUMN_NAME NOT IN
		(
'accountnumber',
'alcoholrecipienttype',
'altemail',
'altname',
'altphone',
'assignedwebsite',
'balancesearch',
'billingratecard',
'buyingreason',
'buyingtimeframe',
'category',
'comments',
'consolbalancesearch',
'consoldaysoverduesearch',
'consoloverduebalancesearch',
'consolunbilledorderssearch',
'contact',
'contactlist',
'creditholdoverride',
'creditlimit',
'custentity_2663_customer_refund',
'custentity_2663_direct_debit',
'custentity_2663_email_address_notif',
'custentity_9572_custref_file_format',
'custentity_9572_dd_file_format',
'custentity_9572_ddcust_entitybank_sub',
'custentity_9572_ddcust_entitybnkformat',
'custentity_9572_refcust_entitybnkformat',
'custentity_9572_refundcust_entitybnk_sub',
'custentity_9997_dd_file_format',
'custentity_cps_bdc_customer_name',
'custentity_cps_bdc_lastupdatedbyimport',
'custentity_cps_bdc_shortname',
'custentity_date_lsa',
'custentity_dic',
'custentity_esc_annual_revenue',
'custentity_esc_industry',
'custentity_esc_no_of_employees',
'custentity_ico',
'custentity_link_lsa',
'custentity_link_name_lsa',
'custentity_tax_contact',
'custentity_tax_contact_first',
'custentity_tax_contact_last',
'custentity_tax_contact_middle',
'custentityreq_bu_4os',
'custentityreq_mod_inv',
'custentitytype_of_backup',
'custentitytype_of_modification',
'defaultbankaccount',
'defaultorderpriority',
'duplicate',
'email',
'emailpreference',
'emailtransactions',
'enddate',
'entitynumber',
'entitynumber',
'entitystatus',
'entitytitle',
'estimatedbudget',
'externalid',
'fax',
'faxtransactions',
'firstname',
'firstorderdate',
'firstsaledate',
'giveaccess',
'homephone',
'isautogeneratedrepresentingentity',
'isbudgetapproved',
'isinactive',
'isperson',
'lastmodifieddate',
'lastname',
'lastorderdate',
'lastsaledate',
'leadsource',
'middlename',
'mobilephone',
'negativenumberformat',
'numberformat',
'oncredithold',
'overduebalancesearch',
'phone',
'prefccprocessor',
'pricelevel',
'printoncheckas',
'printtransactions',
'probability',
'reminderdays',
'representingsubsidiary',
'resalenumber',
'salesreadiness',
'salesrep',
'salutation',
'searchstage',
'shipcomplete',
'shippingcarrier',
'shippingitem',
'sourcewebsite',
'startdate',
'territory',
'thirdpartyacct',
'thirdpartycarrier',
'thirdpartycountry',
'thirdpartyzipcode',
'title',
'unbilledorderssearch',
'url',
'weblead'

		)
		--)
	--		AND
	--	COLUMN_NAME NOT IN
	--				(SELECT Field FROM #temp))
--DROP TABLE #temp;
